ebus store schedule
danielkucera/esp-arduino-ebus pull request #96
Opened 2024-12-22 11:23 UTC by yuhu-

**store**
Implements the storage of active and passive commands. New commands can be added and removed via mqtt. It provides functions for saving, loading and deleting commands in the nvs memory. Commands stored in the nvs are loaded at startup.

**schedule**
This class sends time-controlled active commands to the ebus. All valid received messages are compared with passively defined commands and evaluated if they match. Raw data (including filter function) can also be output. Individual commands are transmitted and the results reported back. The scan results are also published.

2025-01-07 06:47 UTC, danielkucera commented
Hi @yuhu- ,
is this ready for review or still WiP? Can you add it to the title?

2025-01-27 20:31 UTC, yuhu- commented
Hi Daniel! Do you have any idea when you will have time to review it? Maybe you can try out and test the implemented functions.

2025-02-08 13:19 UTC, danielkucera requested changes
Please see my review.

2025-02-08 13:19 UTC, danielkucera commented on src/bus.cpp
these are all formating changes, please provide as a separate PR

2025-02-08 13:19 UTC, danielkucera commented on src/main.cpp
> -
do not move if not necessary

2025-02-08 13:19 UTC, danielkucera commented on src/main.cpp
> +
definitions can remain without ifdef
condition only functions

2025-02-08 13:19 UTC, danielkucera commented on src/main.cpp
> +    "Static IP", "staticIPParam", staticIPValue, STRING_LEN);
unrelated cosmetic, add to formating changes

2025-02-08 13:19 UTC, danielkucera commented on src/main.cpp
> +    iotwebconf::ParameterGroup("ebus", "eBUS configuration");
unrelated cosmetic, add to formating changes

2025-02-08 13:19 UTC, danielkucera commented on src/main.cpp
> +#endif
```suggestion
  s += "<a href='/commands'>Commands</a><br>";
```

2025-02-08 13:33 UTC, danielkucera commented
> Is it realistic for more than one device to be used in the same installation, except in development situations?

Interesting question. Theoretically, one could have one automation/mqtt server controlling multiple ebus installations. This could be solved with parametrizing the `ebus/` prefix of mqtt path so user can specify `ebus/home/`, `ebus/summer_house/` or `ebus1/` `ebus2/` etc.

I would maybe start by having it defined as #define or a const string not necessarily a config param.
I leave the decision on you.

2025-02-08 13:40 UTC, yuhu- commented on src/main.cpp
> +#endif
wouldn't there be a dead link without the callback ?

> configServer.on("/commands", [] { handleCommands(); });

2025-02-08 13:55 UTC, yuhu- commented on src/main.cpp
> -
pwm_value is below the network configuration on the config page. I would prefer to use the same order in the code.

2025-02-08 14:02 UTC, danielkucera commented on src/main.cpp
> +#endif
It would but 404 is okay

2025-02-08 14:04 UTC, danielkucera commented on src/main.cpp
> -
okay

2025-02-08 14:49 UTC, danielkucera commented on src/main.cpp
can you somehow deal with the commented portions of code?
it all seems to deal with some `external bus request`

2025-02-08 14:59 UTC, yuhu- commented on src/main.cpp
I will remove this approach because 
* I have some problems with the current arbitration timing and  
* the internal bus request works pretty well on my adapter.

2025-02-08 15:07 UTC, danielkucera commented
also please rebase to latest master, ci build has been fixed

2025-02-08 16:01 UTC, danielkucera approved these changes
From my side it is ready to merge.
Shall I merge?

2025-02-08 16:35 UTC, yuhu- commented
I think so too. The problem with more than one active device is still open. At first I thought it would be easy to change, but there are a few pitfalls to solve. If there really is a need, we could still change it in the future.

2025-02-08 16:44 UTC, merged

2025-02-08 16:44 UTC, danielkucera commented
Thank you.

2025-02-08 16:56 UTC, danielkucera commented
@yuhu- , could you please write a few lines how to start using the feature?
How to config mqtt, how to do a scan, how to prepare commands, etc.?